name: smartcadd-test
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.10
    - pip
    - pymol-open-source
    - h5py
    - openbabel
    - pdbfixer
    - rdkit
    - numpy
    - pandas
    - pip:
          - deepchem
          - xtb
          - openmm
          - mdanalysis
          - pybel
          - torch
